import type { Option } from "@/types";

/**
 * Generated by `npx tsx scripts/load-answer-key.ts answer-key.csv`.
 * Leave this empty until the official NTA answer key is loaded.
 */
export const ANSWER_KEY: Record<string, Option> = {};
