#!/usr/bin/env python3
"""Render the Biology categorization PDF (Q91-Q180)."""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _pdf_render import render  # noqa: E402

OUT = Path("docs/NEET2026-Biology-Categorization.pdf")

DISTRIBUTION = [
    ("1", "Diversity in Living World", 7, "Q99, Q105, Q121, Q137, Q139, Q156, Q176"),
    ("2", "Structural Organisation in Animals and Plants", 9,
     "Q107, Q109, Q114, Q120, Q128, Q130, Q135, Q136, Q138"),
    ("3", "Cell Structure and Function", 10,
     "Q91, Q101, Q102, Q104, Q127, Q133, Q141, Q152, Q153, Q177"),
    ("4", "Plant Physiology", 7, "Q96, Q97, Q100, Q106, Q112, Q124, Q129"),
    ("5", "Human Physiology", 12,
     "Q140, Q143, Q145, Q146, Q148, Q150, Q159, Q161, Q168, Q172, Q173, Q180"),
    ("6", "Reproduction", 8, "Q108, Q115, Q117, Q142, Q151, Q154, Q163, Q169"),
    ("7", "Genetics and Evolution", 14,
     "Q92, Q94, Q95, Q103, Q111, Q119, Q131, Q157, Q158, Q160, Q166, Q174, Q175, Q179"),
    ("8", "Biology and Human Welfare", 4, "Q149, Q164, Q165, Q167"),
    ("9", "Biotechnology and Its Applications", 8,
     "Q98, Q110, Q113, Q123, Q132, Q144, Q147, Q171"),
    ("10", "Ecology and Environment", 11,
     "Q93, Q116, Q118, Q122, Q125, Q126, Q134, Q155, Q162, Q170, Q178"),
]

CLASS_SPLIT = [
    "<b>Class XI</b> units (1\u20135): ~45 questions \u2014 Diversity, Structure, Cell, Plant Physiology, Human Physiology",
    "<b>Class XII</b> units (6\u201310): ~45 questions \u2014 Reproduction, Genetics/Evolution, Human Welfare, Biotech, Ecology",
]

ROWS = [
    (91, "A", "3 \u2014 Cell Structure and Function",
     "Cell division \u2014 phases of the cell cycle",
     "Match G1, S, G2, M phases to their key activities (growth, DNA replication, mitosis)."),
    (92, "A", "7 \u2014 Genetics and Evolution",
     "Deviations from Mendelism \u2014 incomplete dominance, codominance, multiple alleles",
     "Match each inheritance pattern with its classic example (e.g., incomplete dominance \u2192 Antirrhinum)."),
    (93, "B", "10 \u2014 Ecology and Environment",
     "Biodiversity loss \u2014 habitat loss; extinction examples",
     "Amazon deforestation for soy \u2192 habitat loss; Steller\u2019s sea cow and passenger pigeon hunted to extinction."),
    (94, "B", "7 \u2014 Genetics and Evolution",
     "Molecular basis of inheritance \u2014 transcription unit (promoter, structural gene, terminator)",
     "Identify true statements about the three regions of a transcription unit and their orientation."),
    (95, "A", "7 \u2014 Genetics and Evolution",
     "Sex determination \u2014 haplodiploidy in honeybees",
     "Fertilised diploid eggs \u2192 females; unfertilised haploid eggs \u2192 drones (males)."),
    (96, "D", "4 \u2014 Plant Physiology",
     "Cellular respiration \u2014 site of glycolysis, ETS, TCA",
     "Glycolysis \u2192 cytoplasm; ETS \u2192 inner mitochondrial membrane; TCA \u2192 mitochondrial matrix."),
    (97, "A", "4 \u2014 Plant Physiology",
     "Photosynthesis \u2014 Calvin cycle ATP/NADPH stoichiometry",
     "Per glucose, Calvin cycle consumes 18 ATP and 12 NADPH (3 ATP + 2 NADPH per CO2 \u00d7 6)."),
    (98, "A", "9 \u2014 Biotechnology and Its Applications",
     "Applications of biotechnology \u2014 GMOs, recombinant insulin, gene therapy",
     "Match: GMO \u2192 Bt cotton; recombinant insulin \u2192 Humulin; etc."),
    (99, "B", "1 \u2014 Diversity in Living World",
     "Plant classification \u2014 gymnosperms (naked seeds)",
     "Pinus is a gymnosperm; its ovules are borne exposed on megasporophylls (not enclosed in an ovary)."),
    (100, "C", "4 \u2014 Plant Physiology",
     "Photosynthesis \u2014 Calvin cycle carboxylation enzyme",
     "RuBisCO (Ribulose-1,5-bisphosphate carboxylase/oxygenase) catalyses CO2 fixation onto RuBP."),
    (101, "A", "3 \u2014 Cell Structure and Function",
     "Biomolecules \u2014 enzymes, alkaloids, lectins, drugs",
     "Match trypsin (enzyme), morphine (alkaloid), concanavalin A (lectin), and a drug to their categories."),
    (102, "B", "3 \u2014 Cell Structure and Function",
     "Biomolecules \u2014 amino acid structure",
     "Amino acids have an \u03b1-carbon bearing \u2013NH2, \u2013COOH, \u2013H, and an R-group \u2014 substituted methanes; zwitterions at neutral pH."),
    (103, "C", "7 \u2014 Genetics and Evolution",
     "Mendelian disorders \u2014 sickle-cell anaemia mutation",
     "Point mutation in \u03b2-globin gene: Glu \u2192 Val at the 6th amino-acid position."),
    (104, "D", "3 \u2014 Cell Structure and Function",
     "Nucleus and nucleolus \u2014 site of rRNA synthesis",
     "Nucleolus is the dense sub-nuclear body where rRNA is transcribed and ribosomal subunits are assembled."),
    (105, "D", "1 \u2014 Diversity in Living World",
     "Taxonomy \u2014 binomial nomenclature rules",
     "Italics in print / underline when handwritten; genus capitalised; species lowercase; etc."),
    (106, "D", "4 \u2014 Plant Physiology",
     "Plant growth regulators \u2014 auxins, gibberellins, cytokinins, ethylene, ABA",
     "Match 2,4-D (herbicide), GA3 (malting), cytokinin (cell division), ABA (dormancy) to functions."),
    (107, "A", "2 \u2014 Structural Organisation in Animals and Plants",
     "Plant anatomy \u2014 conjunctive tissue, Casparian strips, endodermis, pericycle",
     "Match anatomical terms (conjunctive tissue between xylem & phloem; Casparian strips in endodermis) to their definitions."),
    (108, "D", "6 \u2014 Reproduction",
     "Sexual reproduction in flowering plants \u2014 pollination types (autogamy, geitonogamy, xenogamy)",
     "Xenogamy alone introduces genetically different pollen (from a different plant) to the stigma."),
    (109, "A", "2 \u2014 Structural Organisation in Animals and Plants",
     "Morphology \u2014 heterophylly and environmental (phenotypic) plasticity",
     "Different leaf forms on the same plant in response to environmental cues = environmental / phenotypic plasticity."),
    (110, "A", "9 \u2014 Biotechnology and Its Applications",
     "Tools of recombinant DNA \u2014 restriction endonucleases",
     "Identify which statements about restriction enzymes are NOT true (\"molecular scissors\", specific recognition sites, etc.)."),
    (111, "B", "7 \u2014 Genetics and Evolution",
     "Molecular basis of inheritance \u2014 DNA fingerprinting steps",
     "Correct order: isolate DNA + digest with restriction enzymes \u2192 electrophoresis \u2192 blotting \u2192 hybridisation with VNTR probe \u2192 autoradiography."),
    (112, "B", "4 \u2014 Plant Physiology",
     "Photosynthesis \u2014 PSII water splitting; C3 vs C4 pathway",
     "Identify the incorrect photosynthesis statement (e.g., water splitting at PSII, C4 plants still use C3 cycle for biosynthesis)."),
    (113, "B", "9 \u2014 Biotechnology and Its Applications",
     "Plant biotechnology \u2014 somatic hybridisation (protoplast fusion)",
     "Order: isolate single cells \u2192 digest cell walls \u2192 isolate naked protoplasts \u2192 fuse \u2192 culture \u2192 regenerate hybrid plants."),
    (114, "C", "2 \u2014 Structural Organisation in Animals and Plants",
     "Plant anatomy \u2014 bulliform (motor) cells in grasses",
     "Large thin-walled epidermal cells; turgid \u2192 leaf flat; flaccid \u2192 leaf rolls to reduce transpiration."),
    (115, "D", "6 \u2014 Reproduction",
     "Sexual reproduction in flowering plants \u2014 microsporogenesis sequence",
     "Sporogenous tissue \u2192 pollen mother cells \u2192 microspore tetrads \u2192 pollen grains."),
    (116, "D", "10 \u2014 Ecology and Environment",
     "Biodiversity conservation \u2014 in situ vs ex situ",
     "In situ = protection of species in their natural habitat (national parks, biosphere reserves); seed banks / safari parks are ex situ."),
    (117, "C", "6 \u2014 Reproduction",
     "Double fertilisation in angiosperms \u2014 ploidy of cells (n, 2n, 3n)",
     "Egg/synergids/antipodals = n; zygote = 2n; primary endosperm nucleus / endosperm = 3n."),
    (118, "D", "10 \u2014 Ecology and Environment",
     "Sixth mass extinction \u2014 unprecedented current rate of species loss",
     "Current extinction rate is several orders of magnitude higher than the geological background rate."),
    (119, "D", "7 \u2014 Genetics and Evolution",
     "Gene expression regulation \u2014 lac operon",
     "lacZ \u2192 \u03b2-galactosidase; lacY \u2192 permease; lacA \u2192 transacetylase; lacI \u2192 repressor."),
    (120, "A", "2 \u2014 Structural Organisation in Animals and Plants",
     "Inflorescence \u2014 racemose (acropetal succession)",
     "Main axis grows indefinitely; older flowers towards base, younger ones towards apex."),
    (121, "B", "1 \u2014 Diversity in Living World",
     "Whittaker\u2019s five-kingdom classification \u2014 criteria",
     "Cell structure (pro/eu), body organisation (uni/multi), mode of nutrition, ecological role, phylogeny."),
    (122, "A", "10 \u2014 Ecology and Environment",
     "Biodiversity loss \u2014 \u2018Evil Quartet\u2019 (Wilson)",
     "Habitat loss & fragmentation, over-exploitation, alien species invasion, co-extinctions."),
    (123, "D", "9 \u2014 Biotechnology and Its Applications",
     "Tools of biotechnology \u2014 PCR cycle (denaturation, annealing, extension)",
     "Correct chronological steps of one PCR cycle: melt strands \u2192 anneal primers \u2192 Taq polymerase extends."),
    (124, "C", "4 \u2014 Plant Physiology",
     "Respiration \u2014 Respiratory Quotient (RQ)",
     "RQ = volume of CO2 evolved / volume of O2 consumed; varies with substrate (carbs = 1, fats < 1, organic acids > 1)."),
    (125, "D", "10 \u2014 Ecology and Environment",
     "Biodiversity \u2014 bioprospecting definition",
     "Bioprospecting is the systematic exploration of molecular, genetic and species-level diversity for economically valuable products."),
    (126, "D", "10 \u2014 Ecology and Environment",
     "Ecosystem \u2014 decomposition terms (detritus, fragmentation, leaching, humification, mineralisation)",
     "Match each decomposition term to its correct definition."),
    (127, "B", "3 \u2014 Cell Structure and Function",
     "Biomolecules \u2014 lipids, proteins (polypeptides), nucleic acids",
     "Identify which biomolecule statements are correct: lipids hydrophobic; proteins = chains of amino acids; etc."),
    (128, "C", "2 \u2014 Structural Organisation in Animals and Plants",
     "Plant anatomy \u2014 root zones (meristem, elongation, maturation / root hair)",
     "Root hairs originate from the maturation (root-hair) zone of the root epidermis."),
    (129, "D", "4 \u2014 Plant Physiology",
     "Plant growth and development \u2014 phase of cell elongation",
     "Elongation phase: rapid vacuolation, cell-wall loosening, increase in cell size \u2014 nuclei become less conspicuous, not more."),
    (130, "A", "2 \u2014 Structural Organisation in Animals and Plants",
     "Plant families \u2014 Solanaceae floral formula",
     "Solanaceae: \u2295 \u2640 K(5) C(5) A5 G(2) \u2014 actinomorphic, bisexual, pentamerous, syncarpous."),
    (131, "C", "7 \u2014 Genetics and Evolution",
     "Molecular basis \u2014 DNA packaging, histones, nucleosome",
     "Histone octamer (2 each of H2A, H2B, H3, H4); histones are positively charged basic proteins; ~200 bp wraps each nucleosome."),
    (132, "C", "9 \u2014 Biotechnology and Its Applications",
     "Tools of biotechnology \u2014 cutting, separating, visualising DNA",
     "Restriction enzymes cut DNA; agarose-gel electrophoresis separates fragments; ethidium-bromide / UV visualisation."),
    (133, "C", "3 \u2014 Cell Structure and Function",
     "Biomolecules \u2014 protein structure (primary, secondary \u03b1-helix, tertiary, quaternary)",
     "Secondary structure = \u03b1-helix / \u03b2-sheet stabilised by H-bonds between backbone atoms."),
    (134, "A", "10 \u2014 Ecology and Environment",
     "Ecosystem \u2014 GPP, NPP, secondary productivity",
     "GPP = total carbon fixed; NPP = GPP \u2212 R (energy available to consumers); secondary productivity = rate of consumer assimilation."),
    (135, "C", "2 \u2014 Structural Organisation in Animals and Plants",
     "Flower \u2014 types of placentation",
     "Marginal \u2192 Pea; axile \u2192 China rose / lemon; parietal \u2192 mustard; free central \u2192 Dianthus; basal \u2192 sunflower."),
    (136, "C", "2 \u2014 Structural Organisation in Animals and Plants",
     "Frog anatomy \u2014 hepatic portal system, cranial nerves",
     "Identify correct frog statements (hepatic portal vein takes blood from gut \u2192 liver; frog has 10 pairs of cranial nerves)."),
    (137, "A", "1 \u2014 Diversity in Living World",
     "Class Aves \u2014 flightless bird with paddle-like forelimbs",
     "Penguin: flightless bird whose wings are modified into flippers / paddles adapted for swimming."),
    (138, "D", "2 \u2014 Structural Organisation in Animals and Plants",
     "Frog \u2014 sexual dimorphism",
     "Male frogs have vocal sacs and nuptial pads; \"bulging eyes\" is NOT a male-distinguishing feature."),
    (139, "A", "1 \u2014 Diversity in Living World",
     "Animal classification \u2014 Cyclostomata (Class Agnatha)",
     "Cartilage endoskeleton, ecto-parasitic circular sucking mouth, 6\u201315 pairs of gill slits, no paired fins / scales \u2192 lamprey / hagfish."),
    (140, "C", "5 \u2014 Human Physiology",
     "Breathing and respiration \u2014 ordered steps",
     "Pulmonary ventilation \u2192 gas exchange across alveoli \u2192 transport in blood \u2192 diffusion at tissues \u2192 cellular respiration."),
    (141, "D", "3 \u2014 Cell Structure and Function",
     "Cell organelles \u2014 non-membrane-bound, present in pro- & eukaryotes",
     "Ribosomes are non-membrane-bound and present in both prokaryotes and eukaryotes."),
    (142, "C", "6 \u2014 Reproduction",
     "Reproductive health \u2014 assisted reproductive technologies (GIFT)",
     "GIFT (Gamete Intrafallopian Transfer): transfer of gametes directly into the fallopian tube for in vivo fertilisation."),
    (143, "B", "5 \u2014 Human Physiology",
     "Locomotion and movement \u2014 mechanism of muscle contraction",
     "Motor neuron \u2192 sarcolemma \u2192 sarcoplasmic reticulum releases Ca2+ \u2192 troponin\u2013tropomyosin \u2192 cross-bridge cycle."),
    (144, "B", "9 \u2014 Biotechnology and Its Applications",
     "Cloning vectors \u2014 pBR322, BamHI, antibiotic-resistance selection",
     "BamHI site in pBR322 lies within the tet gene \u2192 insertional inactivation \u2192 select on ampicillin, screen for tetracycline sensitivity."),
    (145, "A", "5 \u2014 Human Physiology",
     "Neural control and coordination \u2014 chemical synapse",
     "Neurotransmitter binds receptors on the post-synaptic membrane (not the pre-synaptic membrane)."),
    (146, "B", "5 \u2014 Human Physiology",
     "Locomotion and movement \u2014 axial skeleton (skull, vertebrae, ribs)",
     "Human skull is dicondylic; 7 cervical vertebrae; rib classification (true / false / bicephalic) \u2014 evaluate which statements are correct."),
    (147, "B", "9 \u2014 Biotechnology and Its Applications",
     "Applications in health \u2014 \u03b1-1 antitrypsin for emphysema",
     "Recombinant \u03b1-1 antitrypsin is used to treat hereditary emphysema (genetic AAT deficiency)."),
    (148, "C", "5 \u2014 Human Physiology",
     "Body fluids and circulation \u2014 Rh blood grouping, erythroblastosis foetalis",
     "EBF occurs when an Rh\u2212 mother carries an Rh+ fetus (after first sensitisation); identify incorrect Rh-compatibility claims."),
    (149, "A", "8 \u2014 Biology and Human Welfare",
     "Drug and alcohol abuse \u2014 effects of nicotine, opioids, cannabinoids, cocaine",
     "Match each drug to its primary physiological effect (e.g., nicotine \u2192 stimulant via catecholamines)."),
    (150, "B", "5 \u2014 Human Physiology",
     "Locomotion and movement \u2014 muscular/skeletal disorders",
     "Tetany \u2014 muscle spasms from low Ca2+; arthritis \u2014 joint inflammation; osteoporosis; myasthenia gravis; muscular dystrophy."),
    (151, "C", "6 \u2014 Reproduction",
     "Reproductive health \u2014 contraceptive methods (IUDs)",
     "Progestasert \u2192 hormone-releasing IUD; Multiload 375 \u2192 Cu-releasing IUD; LNG-20; CuT etc."),
    (152, "D", "3 \u2014 Cell Structure and Function",
     "Cell membrane \u2014 fluid-mosaic model, lipid bilayer, proteins",
     "Identify correct membrane statements (~52% protein in RBC membrane, phospholipid bilayer); mesosomes belong to prokaryotes."),
    (153, "D", "3 \u2014 Cell Structure and Function",
     "Cell organelles \u2014 endomembrane system (ER, Golgi, lysosomes, vesicles)",
     "Endomembrane system: nuclear envelope, ER, Golgi, lysosomes, vesicles \u2014 mitochondria, plastids, peroxisomes are NOT part of it."),
    (154, "A", "6 \u2014 Reproduction",
     "Human reproduction \u2014 embryonic developmental milestones (gestational weeks)",
     "First movement & hair on head \u2192 ~20 weeks; eyelashes by ~24 wks; full term \u2192 ~38\u201340 wks."),
    (155, "C", "10 \u2014 Ecology and Environment",
     "Population interactions \u2014 sexual deceit (orchid \u2013 wasp mimicry)",
     "Mediterranean orchid Ophrys mimics female bee/wasp to attract males for pollination \u2014 pseudo-copulation \u2192 sexual deceit."),
    (156, "A", "1 \u2014 Diversity in Living World",
     "Animal classification \u2014 Class Osteichthyes (bony fishes)",
     "Identify the option containing only bony fishes (e.g., Catla, Labeo, sea horse); exclude Chondrichthyes / non-fish."),
    (157, "A", "7 \u2014 Genetics and Evolution",
     "Biological evolution \u2014 geological timeline of life",
     "65 mya \u2192 K-Pg extinction (dinosaurs); 500 mya \u2192 invertebrate radiation; 200 mya \u2192 mammals appear; etc."),
    (158, "B", "7 \u2014 Genetics and Evolution",
     "Sex determination / gametogenesis \u2014 haploid gametes by mitosis (honeybee drones)",
     "Drones are haploid (parthenogenetic) and produce sperm by mitotic divisions, not meiosis."),
    (159, "D", "5 \u2014 Human Physiology",
     "Body fluids and circulation \u2014 differential WBC count",
     "Given 8000 WBC/mm\u00b3 with eosinophils ~1\u20136% and lymphocytes ~20\u201345%, compute approximate counts."),
    (160, "D", "7 \u2014 Genetics and Evolution",
     "ABO blood group \u2014 multiple alleles, Mendelian probability",
     "Heterozygous A (IA i) \u00d7 heterozygous B (IB i) \u2192 1 AB : 1 A : 1 B : 1 O \u2192 probability of given offspring blood group."),
    (161, "A", "5 \u2014 Human Physiology",
     "Excretion \u2014 renin\u2013angiotensin\u2013aldosterone system (RAAS)",
     "Order: \u2193BP/GFR \u2192 renin from JGA \u2192 angiotensin I \u2192 II \u2192 vasoconstriction + aldosterone \u2192 Na\u207a/H2O reabsorption."),
    (162, "A", "10 \u2014 Ecology and Environment",
     "Population interactions \u2014 mutualism, parasitism, amensalism, predation, competition",
     "Evaluate statements describing each interaction (mutualism +/+, parasitism +/\u2212, amensalism 0/\u2212, etc.)."),
    (163, "A", "6 \u2014 Reproduction",
     "Human reproduction \u2014 spermatogenesis",
     "Spermatogonia divide mitotically \u2192 primary spermatocyte (2n) \u2192 meiosis I \u2192 secondary spermatocyte (n) \u2192 meiosis II \u2192 spermatids."),
    (164, "A", "8 \u2014 Biology and Human Welfare",
     "Human disease \u2014 Plasmodium life cycle (malaria)",
     "Sequence in human host: sporozoites injected by mosquito \u2192 liver (exo-erythrocytic) \u2192 RBC \u2192 trophozoite \u2192 schizont \u2192 merozoite \u2192 gametocytes."),
    (165, "C", "8 \u2014 Biology and Human Welfare",
     "Microbes in human welfare \u2014 microbial bioactive molecules",
     "Streptokinase \u2192 dissolve clots; statins \u2192 cholesterol-lowering; cyclosporin A \u2192 immunosuppressant; LAB \u2192 curd."),
    (166, "C", "7 \u2014 Genetics and Evolution",
     "Evolution \u2014 convergent vs divergent (homologous vs analogous structures)",
     "Whale and bat forelimbs are homologous (divergent evolution) \u2014 NOT an example of convergent evolution."),
    (167, "D", "8 \u2014 Biology and Human Welfare",
     "Microbes in food processing \u2014 Swiss cheese",
     "Propionibacterium sharmanii ferments lactic acid producing CO2 \u2192 large holes in Swiss cheese."),
    (168, "D", "5 \u2014 Human Physiology",
     "Chemical coordination \u2014 adrenal hormones (cortisol, aldosterone)",
     "Cortisol \u2192 anti-inflammatory / stress response; aldosterone \u2192 Na\u207a and water reabsorption from renal tubules."),
    (169, "B", "6 \u2014 Reproduction",
     "Human reproduction \u2014 layers around the ovum",
     "Outer \u2192 inner: corona radiata \u2192 zona pellucida \u2192 plasma membrane of the egg."),
    (170, "B", "10 \u2014 Ecology and Environment",
     "Populations \u2014 Verhulst\u2013Pearl logistic growth",
     "dN/dt = rN \u00d7 (K \u2212 N)/K, where K is the carrying capacity (sigmoid curve)."),
    (171, "A", "9 \u2014 Biotechnology and Its Applications",
     "Applications in agriculture \u2014 Bt crops, Cry proteins",
     "cryIAc \u2192 cotton bollworms; cryIIAb \u2192 corn borer; cryIAb similar; specific Cry proteins target specific insect orders."),
    (172, "D", "5 \u2014 Human Physiology",
     "Excretion \u2014 Juxta Glomerular Apparatus (JGA)",
     "JGA components: macula densa (DCT) + juxtaglomerular cells (afferent arteriole) + extraglomerular mesangial cells."),
    (173, "B", "5 \u2014 Human Physiology",
     "Respiration \u2014 modes of breathing across animals",
     "Molluscs \u2192 branchial (gills); Reptiles \u2192 pulmonary only; Adult amphibians \u2192 pulmonary + cutaneous; Amoeba \u2192 cellular / by diffusion."),
    (174, "B", "7 \u2014 Genetics and Evolution",
     "Genetic code \u2014 sickle-cell anaemia mutant codon",
     "Normal codon GAG (Glu) \u2192 mutant GUG (Val) at the 6th position of \u03b2-globin \u2192 HbS \u2192 polymerisation and sickling."),
    (175, "C", "7 \u2014 Genetics and Evolution",
     "Sex determination \u2014 XO system (grasshopper)",
     "Female grasshopper = XX (2n + 2 chromosomes); male = XO (2n + 1) \u2014 one fewer chromosome than the female."),
    (176, "B", "1 \u2014 Diversity in Living World",
     "Animal kingdom \u2014 characteristic features (Platyhelminthes, Echinodermata, etc.)",
     "Platyhelminthes \u2192 incomplete digestive system (true); adult echinoderms \u2192 radial symmetry (so claim of bilateral is false)."),
    (177, "C", "3 \u2014 Cell Structure and Function",
     "Biomolecules \u2014 enzyme classification (IUBMB classes)",
     "Reaction cleaves C\u2013C bond, forms C=C without hydrolysis / oxidation \u2192 enzyme is a LYASE."),
    (178, "B", "10 \u2014 Ecology and Environment",
     "Ecosystem \u2014 ecological pyramids (number, biomass, energy)",
     "Pyramid of energy is always upright; biomass / number pyramids can be inverted (e.g., parasite trees, marine ecosystems)."),
    (179, "A", "7 \u2014 Genetics and Evolution",
     "Human evolution \u2014 ancestral sequence",
     "Ramapithecus \u2192 Australopithecus \u2192 Homo habilis \u2192 Homo erectus \u2192 Neanderthal \u2192 Homo sapiens."),
    (180, "B", "5 \u2014 Human Physiology",
     "Breathing \u2014 respiratory volumes (TV, IRV, ERV, RV)",
     "Tidal Volume \u2248 500 mL; IRV \u2248 2500\u20133000 mL; ERV \u2248 1000\u20131100 mL; Residual Volume \u2248 1100\u20131200 mL."),
]

NOTES = [
    ("Q109 (heterophylly)",
     "Sits between Unit 2 (Structural Organisation \u2014 leaf morphology) and Unit 4 (Plant Physiology \u2014 growth/development). Classified under Unit 2 since the question is fundamentally about morphological variation; the developmental explanation is secondary."),
    ("Q111 (DNA fingerprinting)",
     "NCERT places DNA fingerprinting under the Molecular Basis of Inheritance chapter (Unit 7), even though it uses recombinant-DNA tools that overlap with Unit 9."),
    ("Q117 (ploidy in angiosperms)",
     "Question is about cell ploidy during double fertilisation \u2014 placed under Unit 6 (Reproduction); ploidy as a concept also belongs to Unit 3 (Cell Cycle)."),
    ("Q125 (bioprospecting)",
     "Bioprospecting is taught in NCERT under the Biodiversity & Conservation chapter (Unit 10). Has obvious overlap with Unit 9 (biotech applications)."),
    ("Q147 (\u03b1-1 antitrypsin)",
     "Classified under Unit 9 (Biotechnology in Health) since the question is about a recombinant therapeutic protein. The underlying disease (emphysema) belongs to Unit 5."),
    ("Q165 (streptokinase / statins)",
     "Both are microbial-derived bioactive molecules; NCERT covers them under \"Microbes in Human Welfare\" \u2192 Unit 8."),
    ("Q173 (modes of respiration)",
     "Crosses Unit 1 (animal diversity) and Unit 5 (Breathing & Respiration). Placed under Unit 5 because the question is fundamentally about respiratory mechanisms."),
    ("Q177 (lyase enzyme class)",
     "Enzyme nomenclature/classification is in NCERT under Biomolecules (Unit 3 \u2014 Cell Structure and Function)."),
]


if __name__ == "__main__":
    render(
        out_path=OUT,
        subject="Biology",
        q_range="Q91\u2013Q180",
        total_q=90,
        sources_blurb=(
            "NEET-UG 2026 syllabus (NMC notification, Notice_20260108180635.pdf, "
            "Biology \u2014 10 units) \u00b7 Question paper + answer key + line-by-line "
            "explanations (questions on pp. 2\u201386, explanations on pp. 87\u2013277)."
        ),
        distribution=DISTRIBUTION,
        class_split=CLASS_SPLIT,
        rows=ROWS,
        notes=NOTES,
    )
