/**
 * Apply an official NEET 2026 answer key CSV to lib/questions.ts.
 *
 * Usage:
 *   npx tsx scripts/load-answer-key.ts answer-key.csv
 *
 * CSV format (header optional):
 *   q_no,correct_option
 *   1,B
 *   2,D
 *   ...
 *
 * Updates the seeded `correct_option` value inside `OPTIONS[i % 4]` by writing a
 * sidecar `lib/answer-key.json` and a small accessor — this avoids regenerating
 * the chapter scaffold in `lib/questions.ts`. The questions module reads the
 * sidecar at boot if present.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const path = process.argv[2];
if (!path) {
  console.error("Usage: tsx scripts/load-answer-key.ts <answer-key.csv>");
  process.exit(1);
}

const raw = readFileSync(resolve(path), "utf8");
const lines = raw.split(/\r?\n/).filter(Boolean);

const map: Record<string, "A" | "B" | "C" | "D"> = {};
for (const line of lines) {
  const [q, opt] = line.split(",").map((s) => s.trim());
  if (!q || !opt) continue;
  if (!/^\d+$/.test(q)) continue;
  const upper = opt.toUpperCase();
  if (upper !== "A" && upper !== "B" && upper !== "C" && upper !== "D") {
    console.warn(`Skipping invalid option for Q${q}: ${opt}`);
    continue;
  }
  const qNo = Number(q);
  if (qNo < 1 || qNo > 180) continue;
  map[String(qNo)] = upper as "A" | "B" | "C" | "D";
}

const count = Object.keys(map).length;
if (count === 0) {
  console.error("No valid rows parsed.");
  process.exit(1);
}

const outPath = resolve("lib/answer-key.ts");
const body = `import type { Option } from "@/types";

// Auto-generated by scripts/load-answer-key.ts on ${new Date().toISOString()}.
// Do not edit by hand — re-run the script with an updated CSV.
export const ANSWER_KEY: Record<string, Option> = ${JSON.stringify(map, null, 2)};
`;
writeFileSync(outPath, body);
console.log(`Wrote ${count} answers to ${outPath}`);
console.log("Restart the dev server or rebuild — lib/questions.ts picks this up automatically.");
